POST http://89.70.240.11:8000/rest/users/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache

{
"username":"xd@fds.dgdfff",
"password":"fdsfsd"
}


### Admin login

POST http://89.70.240.11:8000/rest/users/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache

{
"username":"admin",
"password":"password"
}

### eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTkyNzQwNDYzLCJqdGkiOiIyNGUyNWMxY2M2ODM0NGVhOTNkY2YzNjQyM2U4NDUwMiIsInVzZXJfaWQiOjF9.x9TYcbkfRZR9y-wjoFTKquz86qwRgbPa8oxwsDRXwXA

POST http://89.70.240.11:8000/api/token/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache

{
"username":"xd@fds.dgdfff",
"password":"fdsfsd"
}

###

PATCH http://89.70.240.11:8000/rest/groups/add_user/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTkyNzM5NDM3LCJqdGkiOiIwY2IwZjEwMmI0MWY0YWFkYjIwNDE2NWQxZmVlNTA0MyIsInVzZXJfaWQiOjI4fQ.dbnLhsC4VU4F1e1lKvTuzh418iv-SfBLYWX6aFYwCxw


{
"groupCode":"4444"
}

###

GET http://89.70.240.11:8000/rest/users/28/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTkyNzM5NDM3LCJqdGkiOiIwY2IwZjEwMmI0MWY0YWFkYjIwNDE2NWQxZmVlNTA0MyIsInVzZXJfaWQiOjI4fQ.dbnLhsC4VU4F1e1lKvTuzh418iv-SfBLYWX6aFYwCxw

###

GET http://89.70.240.11:8000/rest/groups/5
Content-Type: application/json
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTkyNzM5NDM3LCJqdGkiOiIwY2IwZjEwMmI0MWY0YWFkYjIwNDE2NWQxZmVlNTA0MyIsInVzZXJfaWQiOjI4fQ.dbnLhsC4VU4F1e1lKvTuzh418iv-SfBLYWX6aFYwCxw

### Group Creation

POST http://89.70.240.11:8000/rest/groups/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTkyNzM5NDM3LCJqdGkiOiIwY2IwZjEwMmI0MWY0YWFkYjIwNDE2NWQxZmVlNTA0MyIsInVzZXJfaWQiOjI4fQ.dbnLhsC4VU4F1e1lKvTuzh418iv-SfBLYWX6aFYwCxw

{
  "name" : "nie mam kurwa pojecia",
  "groupCode" : "9999"
}

###

DELETE http://89.70.240.11:8000/rest/groups/3/
Content-Type: application/json
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTkyNzM5NDM3LCJqdGkiOiIwY2IwZjEwMmI0MWY0YWFkYjIwNDE2NWQxZmVlNTA0MyIsInVzZXJfaWQiOjI4fQ.dbnLhsC4VU4F1e1lKvTuzh418iv-SfBLYWX6aFYwCxw
