version: '2'
services:
 web:
  build: ./E-gzamin-frontend/
  command: npm start
  ports:
   - "80:3000"
 db:
  image: postgres:12.2
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: password
  ports:
   - "5432:5432"
 backend:
  build:
   context: ./E_gzamin_django
   dockerfile: Dockerfile
  command: bash -c "python ./E_gzamin_django/manage.py migrate 
                    && python ./E_gzamin_django/manage.py runserver 0.0.0.0:8000"
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  env_file: .env
