# Generated by Django 3.0.7 on 2020-06-06 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(null=True)),
                ('content', models.TextField()),
                ('courses', models.ManyToManyField(to='E_gzamin_app.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='E_gzamin_app.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(null=True)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxPoints', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isPassed', models.BooleanField()),
                ('completedAt', models.DateTimeField()),
                ('startedAt', models.DateTimeField()),
                ('finishedAt', models.DateTimeField()),
                ('testTemplate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='E_gzamin_app.TestTemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('groupCode', models.CharField(max_length=16)),
                ('openedAt', models.DateTimeField(null=True)),
                ('closedAt', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('passReq', models.DecimalField(decimal_places=2, max_digits=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_gzamin_app.Group')),
                ('testTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_gzamin_app.TestTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(null=True)),
                ('content', models.TextField()),
                ('isCorrect', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_gzamin_app.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
