# Generated by Django 3.0.7 on 2020-06-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_gzamin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('passReq', models.DecimalField(decimal_places=2, max_digits=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_gzamin_app.Group')),
                ('testTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_gzamin_app.TestTemplate')),
            ],
        ),
    ]
