# Generated by Django 3.0.7 on 2020-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_gzamin_app', '0002_designate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='closedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='openedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
